name: 'Run Bat File'
description: 'Run Bat File with parameters'
inputs:
  type:
    description: 'Type'
    required: true
  int1:
    description: 'Number 1'
    required: true
  int2:
    description: 'Number 2'
    required: true
runs:
  using: "composite"
  steps:          
    - run: ${{ github.action_path }}\script.bat ${{ inputs.int1 }} ${{ inputs.int2 }}
      shell: cmd
      if: ${{ inputs.type }} = 'teste'
    - run: ${{ github.action_path }}\script.bat ${{ inputs.int1 }} ${{ inputs.int2 }}
      shell: cmd
      if: ${{ inputs.type }} = 'producao'
