name: 'Run Bat File'
description: 'Run Bat File with parameters'
inputs:
  tipo:
    description: 'Tipo do bat'
    required: true
  int1:
    description: 'Number 1'
    required: true
  int2:
    description: 'Number 2'
    required: true
runs:
  using: "composite"
  steps:          
    - run: ${{ github.action_path }}\script.bat ${{ inputs.int1 }} ${{ inputs.int2 }}
      shell: cmd
      if: ${{ inputs.tipo }} = 'teste'
    - run: ${{ github.action_path }}\script.bat 10 20
      shell: cmd
      if: ${{ inputs.tipo }} = 'producao'
